Dockerfile: fix installation of bindgen-cli
Errored with

```
error: failed to compile `bindgen-cli v0.65.1`, intermediate artifacts can be found at `/tmp/cargo-installmxLBVh`

Caused by:
  package `clap_lex v0.5.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
  Try re-running cargo install with `--locked`
Error: error building at STEP "RUN CARGO_HOME=/opt/cargo cargo install bindgen-cli --version 0.65.1": error while running runtime: exit status 101
```

We do the same fix for cbindgen so that deps don't update unexpectedly.