device_test: fix `undefined reference to screen_process`
No idea what causes it and why only in test_smarteeprom.c, which is simliar to for
example test_usb_composed_ep_in.c, which also does not use any screen
stuff and still compiles.