rust: update toolchain to 1.84.0 and update bindgen/cbindgen
This reduces the binary size by about 3kB.

New now are warnings (which we interpret as errors) about shared mut
refs:

```
 = note: shared references to mutable statics are dangerous; it's undefined behavior if the static is mutated or if a mutable reference is created for it while the shared reference lives
   = note: `-D static-mut-refs` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(static_mut_refs)]`
error: creating a shared reference to mutable static is discouraged
```

The commit includes `UnsafeSyncRefCell` and uses it in some unit tests
to remove the warning. In `src/rust/bitbox02-rust-c/src/workflow.rs`
we disable the warning altogether as it's hard to fix it there, so we
delay it there for a future PR.